service: simple-lambda

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'yarn'
  serverless-offline:
    port: 4000

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, file(config.json):stage, 'dev'}
  region: ${opt:region, file(config.json):region, 'us-east-1'}
  environment:
    REGION: ${self:provider.region}
  versionFunctions: true

functions:
  api:
    handler: src/handler
    name: ${self:provider.stage}-${self:service}-api
    memorySize: 128
    events:
      - http:
          path: api/greeting
          method: GET
