service: aws-nodejs # NOTE: update this with your service name

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'yarn'
  serverless-offline:
    port: 4000

resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: uploadstest-${self:provider.stage}
        AccessControl: Private
        CorsConfiguration:
          CorsRules:
          - AllowedMethods:
            - GET
            - PUT
            - POST
            - HEAD
            AllowedOrigins:
            - "*"
            AllowedHeaders:
            - "*"

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, file(config.json):stage, 'dev'}
  region: ${opt:region, file(config.json):region, 'us-east-1'}
  environment:
    REGION: ${self:provider.region}
    BUCKET: uploadstest-${self:provider.stage}
  versionFunctions: false
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:*"
    Resource: "*"

functions:
  api:
    handler: src/lambda.handler
    name: ${self:provider.stage}-${self:service}-api
    memorySize: 128
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
